version: '3.8'

services:
  image-processor:
    image: image-processor:latest
    container_name: image-processor-service
    restart: always
    env_file:
      - .env

  camera-ingest:
    image: camera-ingest:latest
    container_name: camera-ingest-service
    restart: always
    env_file:
      - .env
