version: '3.8'

services:
  image-processor:
    image: image-processor:latest
    container_name: image-processor-service
    restart: always
    env_file:
      - image-processor/.env

  camera-ingest:
    image: camera-ingest:latest
    container_name: camera-ingest-service
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - camera-ingest/.env
